import UIKit

struct StringConstants {
    static let k: String = ""
    static let kLblSteamB100: String = "STEAM B100"
    static let kLblDec: String = "Dec"
    static let kLbl50th2: String = "50th / 2%"
    static let kLbl0Applied: String = "0 Applied"
    static let kLbl1Dec: String = "1\nDec"
    static let kLblPoints: String = "Points"
    static let kLbl21: String = "21"
    static let kLblRanking2: String = "Ranking\n"
    static let kMsgLocationSteam: String = "Location: STEAM B100"
    static let kMsgAdditionalEvid: String = "Additional Evidence (Optional)"
    static let kLblNewPassword: String = "New Password"
    static let kLblCreateAccount: String = "Create Account"
    static let kLblTimes: String = "Times:\n"
    static let kLbl123456: String = "123456"
    static let kMsgComeOutFriday: String =
        "Come out Friday night to see our Allen Eagles take on the North Crowley Wildcats. The game starts at {Start} and will last until {End}. Hope to see you there!"
    static let kLblFollow: String = "Follow"
    static let kMsgSendCurrentLo: String = "Send Current Location as Evidence"
    static let kLblDec8th4Pm: String = "Dec. 8th @ 4 PM"
    static let kUnableToFetch: String = "Unable to fetch data"
    static let kLbl12: String = "+1"
    static let kLbl10: String = "10"
    static let kLblFriday: String = "Friday\n"
    static let kMsgTimesTuesThu: String = "Times:\nTues/Thur 5-8PM\nSat 10AM-3PM"
    static let kLblSignUp: String = "Sign Up"
    static let kLblMale: String = "Male"
    static let kMsgCsForumProvid: String =
        "CS Forum provides general computer science information and hosts many sub-organizations such as CyberSecurity."
    static let kLblEagleStadium: String = "Eagle Stadium\n"
    static let kLblEngagement: String = "= ENGAGEMENT ="
    static let kMsgForgotPassword: String = "Forgot Password?"
    static let kLblGrade2: String = "Grade"
    static let kLblLocation: String = "Location: "
    static let kLbl257385: String = "257385"
    static let kLblRankingGrade: String = "Ranking\n(Grade)"
    static let kLblCsForum: String = "CS Forum"
    static let kLblReadMore: String = "Read More"
    static let kLblAllenHsPac: String = "Allen HS PAC"
    static let kLblEagle: String = "EAGLE"
    static let kLbl: String = "************"
    static let kLblSubmit: String = "Submit"
    static let kLblRewards: String = "Rewards"
    static let kLbl600900Pm: String = "6:00-9:00 PM"
    static let kLblGrade: String = "(Grade)"
    static let kMsgGregoryBurnham: String = "Gregory Burnham\nGraham Gadd"
    static let kLblSupport: String = "Support"
    static let kMsgPasswordRecove: String = "Password Recovery"
    static let kLblClubs: String = "Clubs"
    static let kMsgMakeSureYouM: String =
        "Make sure you meet the requirements for exam exemptions.\nAttendance:\n3 Absences + 90\n2 Absences + 80\nFines:\nNo Fines\nAll Equipment Check In\nDiscipline:\nNo AEP\nNo ISS/OSS\nNo Tier II/III Honor Code violations"
    static let kMsgEagleStadium1: String = "Eagle Stadium\n155 Rivercrest Dr, Allen TX 75002"
    static let kLblSenior: String = "Senior"
    static let kLblEvent: String = "Event*"
    static let kLblDec1st8Pm: String = "Dec. 1st @ 8 PM"
    static let kLbl20th1: String = "20th / 1%"
    static let kLbl1: String = "1\n"
    static let kLblStudentId: String = "Student ID"
    static let kLblGender: String = "Gender"
    static let kMsgInsertReasonH: String = "Insert Reason Here"
    static let kLbl5: String = "5"
    static let kMsg155Rivercrest: String = "155 Rivercrest Dr, Allen TX 75002"
    static let kLblRequest: String = "Request"
    static let kLbl400: String = "400"
    static let kMsgSponsorGregor: String = "Sponsor:\nGregory Burnham\nGraham Gadd"
    static let kLblLogin: String = "Login"
    static let kLblEagleRobotics: String = "Eagle Robotics"
    static let kMsgReasonForMiss: String = "Reason for Missed Points*"
    static let kLblCheckIn: String = "Check-In"
    static let kHttpFail: String = "HTTP request failed"
    static let kMsgEagleRobotics: String =
        "Eagle Robotics participates in B.E.S.T. and FRC robotics competitions. We have programming, building, and business opportunities."
    static let kLblPointRequest: String = "Point Request"
    static let kMsgTuesThur58pm: String = "Tues/Thur 5-8PM\nSat 10AM-3PM"
    static let kMsgJewelryClassS: String = "Jewelry Class Showcase"
    static let kLblEvents: String = "Events"
    static let kLblHouse: String = "House"
    static let kLblPassword: String = "Password"
    static let kLblEagleStadium2: String = "Eagle Stadium"
    static let kLblOr: String = "OR"
    static let kLblUploadImage: String = "Upload Image"
    static let kLblSponsor: String = "Sponsor:\n"
    static let kMsgAllenVNorth: String = "Allen v. North Crowley"
    static let kInvalidUrl: String = "Invalid URL"
    static let kMsgFriday60090: String = "Friday\n6:00-9:00 PM"
    static let kLblPointHistory: String = "Point History"
    static let kLblEventCheckIn: String = "Event Check-In"
    static let kLblEnterEvidence: String = "Enter Evidence"
    static let kLblRanking: String = "Ranking"
    static let kMsgFallExamExemp: String = "Fall Exam Exemptions - 50pts"
}
